// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file KJELDAHL_N.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace NeospectraApp
{
    
    public sealed class KJELDAHL_NInput
    {
        public TensorFloat serving_default_input_700; // shape(-1,154)
    }
    
    public sealed class KJELDAHL_NOutput
    {
        public TensorFloat StatefulPartitionedCall00; // shape(-1,1)
    }
    
    public sealed class KJELDAHL_NModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<KJELDAHL_NModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            KJELDAHL_NModel learningModel = new KJELDAHL_NModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<KJELDAHL_NOutput> EvaluateAsync(KJELDAHL_NInput input)
        {
            binding.Bind("serving_default_input_7:0", input.serving_default_input_700);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new KJELDAHL_NOutput();
            output.StatefulPartitionedCall00 = result.Outputs["StatefulPartitionedCall:0"] as TensorFloat;
            return output;
        }
    }
}

